CREATETABLEIFNOTEXISTSusers(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL,
  password_hash VARCHAR(255)NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT'STAFF',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id),
  UNIQUE KEYuq_users_email(
    email
  )
)ENGINE = InnoDBDEFAULTCHARSET = utf8mb4;
